# Formal Verification CI Workflow

name: Formal Verification

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run weekly verification on main branch
    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC

jobs:
  verify-token-contracts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        kani-version: [0.67.0]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        components: rust-src
    
    - name: Install Kani
      run: |
        cargo install --version ${{ matrix.kani-version }} --locked kani-verifier
    
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Build contracts
      working-directory: Contracts
      run: |
        cargo build --workspace
    
    - name: Run formal verification
      working-directory: Contracts/formal-verification
      run: |
        chmod +x tools/run-verification.sh
        ./tools/run-verification.sh full
    
    - name: Upload verification reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: formal-verification-reports
        path: |
          Contracts/formal-verification/reports/
          Contracts/formal-verification/tools/kani-config.json
        retention-days: 30
    
    - name: Check verification results
      run: |
        if [ -f "Contracts/formal-verification/reports/verification-report.json" ]; then
          passed=$(jq -r '.passed_count' Contracts/formal-verification/reports/verification-report.json)
          total=$(jq -r '.total_proofs' Contracts/formal-verification/reports/verification-report.json)
          rate=$(jq -r '.success_rate' Contracts/formal-verification/reports/verification-report.json)
          
          echo "Verification Results:"
          echo "  Passed: $passed/$total"
          echo "  Success Rate: $rate%"
          
          if [ "$rate" != "100" ]; then
            echo "::error::Formal verification failed with $((total - passed)) failed proofs"
            exit 1
          fi
        else
          echo "::error::No verification report generated"
          exit 1
        fi

  verify-with-coverage:
    runs-on: ubuntu-latest
    needs: verify-token-contracts
    if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust with coverage support
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src,llvm-tools-preview
    
    - name: Install Kani with coverage
      run: |
        cargo install --git https://github.com/model-checking/kani --branch main --locked kani-verifier
    
    - name: Run verification with coverage
      working-directory: Contracts/formal-verification
      run: |
        # Run with coverage analysis
        cargo kani --coverage --output-format=json > reports/coverage-report.json
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: verification-coverage-report
        path: Contracts/formal-verification/reports/coverage-report.json

  security-audit:
    runs-on: ubuntu-latest
    needs: verify-token-contracts
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run cargo-audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run cargo-deny
      uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check bans licenses sources

  performance-monitoring:
    runs-on: ubuntu-latest
    needs: verify-token-contracts
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download verification reports
      uses: actions/download-artifact@v3
      with:
        name: formal-verification-reports
        path: reports/
    
    - name: Analyze verification performance
      run: |
        # Extract timing information from reports
        if [ -f "reports/verification-report.json" ]; then
          echo "Performance analysis:"
          # Add performance metrics extraction here
        fi
    
    - name: Report performance to monitoring
      # This would integrate with your monitoring system
      run: |
        echo "Performance data would be sent to monitoring system here"

  notify-results:
    runs-on: ubuntu-latest
    needs: [verify-token-contracts, security-audit]
    if: always()
    
    steps:
    - name: Download all reports
      uses: actions/download-artifact@v3
      with:
        path: all-reports/
    
    - name: Generate summary comment
      if: github.event_name == 'pull_request'
      run: |
        # Generate a summary comment for PR
        echo "## Formal Verification Results" > comment.md
        echo "" >> comment.md
        # Add results summary
        
    - name: Send notification
      if: failure() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
      run: |
        # Send notification about verification failures
        echo "Verification failed on protected branch"